In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.DataFrame([[8 , 8 , 4] , [7 , 9 , 5] , [5 , 12 , 7] , [6 , 10 , 6]], columns=['cgpa' , 'res_score' , 'lpa'])

In [5]:
df

,cgpa,res_score,lpa
0,8,8,4
1,7,9,5
2,5,12,7
3,6,10,6


In [6]:
def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1 , L):
    parameters['W' + str(l)] = np.ones((layer_dims[l-1] , layer_dims[l])) * 0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l] , 1))

  return parameters

In [7]:
initialize_parameters([2 , 2, 1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [8]:
def linear_forward(A_prev , W , b):

  Z = np.dot(W.T , A_prev) + b
  return Z

In [25]:
#Forward Propagation
def L_layer_forward(X , parameters):

  A = X
  L = len(parameters) // 2
  for l in range(1 , L+1):
    A_prev = A
    W1 = parameters['W' + str(l)]
    b1 = parameters['b' + str(l)]

    # print("A" + str(l-1)+ ": " , A_prev)
    # print("W" + str(l)+ ": " , W1)
    # print("b" + str(l)+ ": " , b1)
    # print("--"*20)

    A = linear_forward(A_prev , W1 , b1)
    # print("A"+str(l)+": " , A)
    # print("**"*20)

  return A , A_prev

In [15]:
X = df[['cgpa' , 'res_score']].values[0].reshape(2 , 1)
y = df[['lpa']].values[0][0]

parameters = initialize_parameters([2 , 2, 1])

y_hat , A1 = L_layer_forward(X , parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [16]:
loss = (y - 0.32) ** 2
loss

np.float64(13.5424)

In [21]:
y_hat

np.float64(0.32000000000000006)

In [22]:
def update_parameters(parameters , y , y_hat , A1 , X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat) * A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat) * A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat) * parameters['W2'][0][0] * X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat) * parameters['W2'][0][0] * X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat) * parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat) * parameters['W2'][1][0] * X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat) * parameters['W2'][1][0] * X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat) * parameters['W2'][1][0])

  return parameters


In [23]:
update_parameters(parameters , y , y_hat , A1 , X)

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [24]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [26]:
parameters = initialize_parameters([2 , 2, 1])
epochs = 75

for i in range(epochs):

  loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa' , 'res_score']].values[j].reshape(2 , 1)
    y = df[['lpa']].values[j][0]

    y_hat , A1 = L_layer_forward(X , parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters , y , y_hat , A1 , X)

    loss_ = (y - y_hat) ** 2
    loss.append(loss_)

  print('Epoch - ',i+1,'Loss - ',np.array(loss).mean())

parameters

Epoch -  1 Loss -  25.302541015384726
Epoch -  2 Loss -  18.308728586218738
Epoch -  3 Loss -  9.510715407674606
Epoch -  4 Loss -  3.329550090243517
Epoch -  5 Loss -  1.3937107926220875
Epoch -  6 Loss -  1.1898627591856838
Epoch -  7 Loss -  1.2322804391751778
Epoch -  8 Loss -  1.261151518873883
Epoch -  9 Loss -  1.272244947738656
Epoch -  10 Loss -  1.2761926208831529
Epoch -  11 Loss -  1.2777465916749513
Epoch -  12 Loss -  1.2785540938937354
Epoch -  13 Loss -  1.279148829745167
Epoch -  14 Loss -  1.279699667366474
Epoch -  15 Loss -  1.2802593513437437
Epoch -  16 Loss -  1.280844100664364
Epoch -  17 Loss -  1.2814587245589943
Epoch -  18 Loss -  1.282104487956583
Epoch -  19 Loss -  1.2827815606659365
Epoch -  20 Loss -  1.2834897759367303
Epoch -  21 Loss -  1.2842288641207933
Epoch -  22 Loss -  1.284998524231225
Epoch -  23 Loss -  1.2857984457092249
Epoch -  24 Loss -  1.2866283149731312
Epoch -  25 Loss -  1.2874878173312359
Epoch -  26 Loss -  1.2883766374770043
Epoc

{'W1': array([[-0.04264665,  0.69031959],
        [-0.04785496,  0.82509822]]),
 'b1': array([[0.02224061],
        [0.0292282 ]]),
 'W2': array([[0.3661003 ],
        [0.45755239]]),
 'b2': array([[0.45795754]])}

In [27]:
import tensorflow
from tensorflow import keras

from tensorflow.keras import Sequential
from keras.layers import Dense

In [28]:
model = Sequential()

model.add(Dense(2 , activation='linear' , input_dim=2))
model.add(Dense(1 , activation='linear'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [29]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.get_weights()

[array([[ 0.16469288, -0.7957844 ],
        [ 0.07655096, -0.8718641 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.2471017],
        [ 0.9626235]], dtype=float32),
 array([0.], dtype=float32)]

In [31]:
new_weights = [np.array([[0.1 , 0.1] , [0.1 , 0.1]] , dtype=np.float32),
               np.array([0. , 0.] , dtype=np.float32),
               np.array([[0.1] , [0.1]] , dtype=np.float32),
               np.array([0.] , dtype=np.float32)]

In [32]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss = 'mean_squared_error' , optimizer = optimizer)

In [34]:
model.fit(df.iloc[: , 0:-1].values , df['lpa'].values , epochs = 75 , verbose=1 , batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 83.8066 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 81.5672 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 79.3599
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 77.1918 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 75.0618 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 73.0676 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 70.9503
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 68.8841 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 66.9652 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 65.0233 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 63.0343 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 61.3073
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 59.4129 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 57.6722 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 55.8594 
Epoch 16/75
4/4 ━━━

In [35]:
model.get_weights()

[array([[-0.23150937, -0.46193582],
        [-0.31696418, -0.5405441 ]], dtype=float32),
 array([-0.4000201,  0.3369116], dtype=float32),
 array([[-1.6182698 ],
        [ 0.63703114]], dtype=float32),
 array([0.37717792], dtype=float32)]