In [1]:
import numpy as np

In [2]:
docs = ['go india',
        'india india',
        'jeetega bhai jeetega india jeetega',
        'bharat mata ki jai',
        'kohli kohli',
        'sachin sachin',
        'dhoni dhoni',
        'inquilab zindabad']

In [3]:
#tokenize input data

!pip install tensorflow

from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token='abhijeet')

In [4]:
tokenizer.fit_on_texts(docs)

In [5]:
tokenizer.word_index #dictionary and alloted tokens

{'abhijeet': 1,
 'india': 2,
 'jeetega': 3,
 'kohli': 4,
 'sachin': 5,
 'dhoni': 6,
 'go': 7,
 'bhai': 8,
 'bharat': 9,
 'mata': 10,
 'ki': 11,
 'jai': 12,
 'inquilab': 13,
 'zindabad': 14}

In [6]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 1),
             ('jai', 1),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('inquilab', 1),
             ('zindabad', 1)])

In [7]:
tokenizer.document_count

8

In [8]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[7, 2],
 [2, 2],
 [3, 8, 3, 2, 3],
 [9, 10, 11, 12],
 [4, 4],
 [5, 5],
 [6, 6],
 [13, 14]]

In [9]:
from keras.utils import pad_sequences

sequences =pad_sequences(sequences , padding='post')#apply post padding

In [10]:
sequences

array([[ 7,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 3,  8,  3,  2,  3],
       [ 9, 10, 11, 12,  0],
       [ 4,  4,  0,  0,  0],
       [ 5,  5,  0,  0,  0],
       [ 6,  6,  0,  0,  0],
       [13, 14,  0,  0,  0]], dtype=int32)

In [11]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [12]:
(X_train , y_train) , (X_test , y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [13]:
X_train.shape , X_test.shape

((25000,), (25000,))

In [14]:
print(len(X_train[0]))
print(len(X_train[1]))

218
189


In [21]:
#Apply padding

X_train = pad_sequences(X_train , padding='post' , maxlen=1000)
X_test = pad_sequences(X_test , padding='post' , maxlen=1000)

In [22]:
print(len(X_train[0]))

1000


In [23]:
model = Sequential()

model.add(SimpleRNN(32 , input_shape=(100 , 1) , return_sequences=False))
model.add(Dense(1 , activation='sigmoid'))

model.summary()

/usr/local/lib/python3.13/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.compile(loss='binary_crossentropy' , optimizer='adam' , metrics=['accuracy'])

model.fit(X_train , y_train , epochs=5 , validation_data=(X_test , y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 50s 61ms/step - accuracy: 0.4984 - loss: 0.6947 - val_accuracy: 0.5000 - val_loss: 0.6932
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 46s 59ms/step - accuracy: 0.5044 - loss: 0.6934 - val_accuracy: 0.5000 - val_loss: 0.6938
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 46s 59ms/step - accuracy: 0.4975 - loss: 0.6939 - val_accuracy: 0.5000 - val_loss: 0.6932
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 84s 62ms/step - accuracy: 0.4990 - loss: 0.6940 - val_accuracy: 0.5000 - val_loss: 0.6932
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 46s 59ms/step - accuracy: 0.5008 - loss: 0.6942 - val_accuracy: 0.5000 - val_loss: 0.6932


In [27]:
#Embeddings

model = Sequential()

model.add(Embedding(17 , output_dim=2 , input_length=5))

model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.compile('adam' , 'accuracy')

In [29]:
pred = model.predict(sequences)

print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 662ms/step
[[[ 0.00180082 -0.03471265]
  [ 0.00228268  0.02123913]
  [ 0.01480908 -0.00249225]
  [ 0.01480908 -0.00249225]
  [ 0.01480908 -0.00249225]]

 [[ 0.00228268  0.02123913]
  [ 0.00228268  0.02123913]
  [ 0.01480908 -0.00249225]
  [ 0.01480908 -0.00249225]
  [ 0.01480908 -0.00249225]]

 [[ 0.01800294 -0.01865381]
  [-0.01429933  0.03241949]
  [ 0.01800294 -0.01865381]
  [ 0.00228268  0.02123913]
  [ 0.01800294 -0.01865381]]

 [[ 0.00408962  0.03511581]
  [-0.03199337  0.00342464]
  [ 0.01067622  0.02743388]
  [ 0.03608811  0.04813074]
  [ 0.01480908 -0.00249225]]

 [[-0.04510904 -0.03107362]
  [-0.04510904 -0.03107362]
  [ 0.01480908 -0.00249225]
  [ 0.01480908 -0.00249225]
  [ 0.01480908 -0.00249225]]

 [[ 0.01220932 -0.01961747]
  [ 0.01220932 -0.01961747]
  [ 0.01480908 -0.00249225]
  [ 0.01480908 -0.00249225]
  [ 0.01480908 -0.00249225]]

 [[-0.02771989 -0.03523479]
  [-0.02771989 -0.03523479]
  [ 0.01480908 -0.00249225]
  [ 0.01480908 -0.0024922